extends:
  - ./.eslintrc.dist.yml
  - ./.eslintrc.imports.yml
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/strict-type-checked
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 13
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        ClassDeclaration: true

overrides:
  - files: "*.d.ts"
    rules:
      no-restricted-imports: off
      require-jsdoc: off
