name: CI

on:
  push:
    branches:
      - main
      - github-ci
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
    # paths:
    #   - "connector/**"

jobs:
  connector:
    name: "Host connector"
    runs-on: ubuntu-latest
    env:
      working-directory: ./connector
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        id: zipName
        run: |
          echo "::set-output name=tagname::${GITHUB_REF#refs/*/}"
          echo "::set-output name=filename::gnome-tabsearchprovider-connector.$(date --iso-8601).$(git rev-parse --short HEAD).zip"

      - name: Install dependencies
        run: |
          python3 -m pip install --user meson ninja

      - name: Clippy
        working-directory: ${{ env.working-directory }}
        run: |
          export CARGO_TARGET_DIR=build/target
          cargo clippy -- -D warnings

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: |
          export GIT_HEAD_SHA=$(git rev-parse HEAD)
          meson --prefix=$PWD/dist/usr --sysconfdir=$PWD/dist/etc build
          ninja -C build install

      - name: Create Zip
        working-directory: ${{ env.working-directory }}
        run: |
          cd dist
          zip -r ${{ steps.zipName.outputs.filename }} .

      - name: Upload archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.zipName.outputs.filename }}
          path: ${{ env.working-directory }}/dist/${{ steps.zipName.outputs.filename }}

  shell-extension:
    name: "Shell extension"
    runs-on: ubuntu-latest
    env:
      working-directory: ./shellextension
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        working-directory: ${{ env.working-directory }}
        run: |
          yarn
          yarn eslint "extension/**/*.ts"

  web-extension:
    name: "Web extension"
    runs-on: ubuntu-latest
    env:
      working-directory: ./webextension
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        working-directory: ${{ env.working-directory }}
        run: |
          yarn
          yarn eslint "src/**/*.ts"
