name: Connector Release

on:
  push:
    tags:
      - "connector-v*"

jobs:
  Release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      working-directory: ./connector
    steps:
      - uses: actions/checkout@v2
      - name: Set variables
        id: zipName
        run: |
          echo "::set-output name=tagname::${GITHUB_REF#refs/*/}"
          echo "::set-output name=filename::'gnome-tabsearchprovider-connector.${GITHUB_REF#refs/*/}.zip'"

      - name: Clippy
        working-directory: ${{ env.working-directory }}
        run: |
          cargo clippy -- -D warnings

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y meson ninja-build

      - name: Build
        working-directory: ${{ env.working-directory }}
        run: |
          export GIT_HEAD_SHA=$(git rev-parse HEAD)
          meson --prefix=$PWD/dist --buildtype=release build
          ninja -C build install

      - name: Create Zip
        working-directory: ${{ env.working-directory }}
        run: |
          zip -r "${{ steps.zipName.outputs.filename }}" zip

      - name: Upload archive artifact
        uses: actions/upload-artifact@v2
        with:
          working-directory: ${{ env.working-directory }}
          name: ${{ steps.zipName.outputs.filename }}
          path: ${{ steps.zipName.outputs.filename }}

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          working-directory: ${{ env.working-directory }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.zipName.outputs.tagname }}
          files: ${{ steps.zipName.outputs.filename }}
